[global]
pythonVersion = "3.10"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]            
primaryColor = "#E79898"             
backgroundColor = "#1D1D1B"          
secondaryBackgroundColor = "#FC6C85" 
textColor = "#FFFFFF"                
font = "sans serif"